FROM node:22-bookworm-slim
WORKDIR /app
COPY package.json package-lock.json ./
COPY node_modules ./node_modules
COPY dist ./dist
COPY app ./app
COPY db ./db
COPY drizzle ./drizzle
COPY public ./public
COPY next-env.d.ts tsconfig.json vite.config.ts drizzle.config.ts ./
EXPOSE 3000
CMD ["npm", "run", "start"]
