"use client";
import { useEffect, useState } from "react";
type Article = { id: number; title: string; source: string; tag: string; time: string; status: string; excerpt: string; rewrittenContent?: string; coverImage?: string };
type Settings = { brand: string; brandVisible: boolean; subtitle: string; subtitleVisible: boolean; eyebrow: string; eyebrowVisible: boolean; heroTitle: string; heroTitleVisible: boolean; heroDescription: string; heroDescriptionVisible: boolean };
export default function Feed() {
  const [items, setItems] = useState<Article[]>([]); const [selected, setSelected] = useState<Article | null>(null); const [settings, setSettings] = useState<Settings>({ brand: "极客采集台", brandVisible: true, subtitle: "AI 精选 · 每日更新", subtitleVisible: true, eyebrow: "AI & DEVELOPER DIGEST", eyebrowVisible: true, heroTitle: "今天值得读的技术内容", heroTitleVisible: true, heroDescription: "采集热点，AI 改写，人工审核后发布。", heroDescriptionVisible: true });
  useEffect(() => { fetch("/api/articles").then(r => r.json()).then(x => { const published = (x.items ?? []).filter((a: Article) => a.status === "已发布"); setItems(published); setSelected(published[0] ?? null); }); fetch("/api/settings").then(r => r.json()).then(setSettings); }, []);
  return <main style={{ minHeight: "100vh", background: "#f7f8fb", color: "#172033", fontFamily: "system-ui" }}><header style={{ maxWidth: 1120, margin: "auto", padding: "28px 24px", display: "flex", alignItems: "center" }}>{settings.brandVisible && <b style={{ fontSize: 22 }}>{settings.brand}</b>}{settings.subtitleVisible && <span style={{ marginLeft: 12, color: "#8790a4" }}>{settings.subtitle}</span>}</header><section style={{ maxWidth: 1120, margin: "30px auto", padding: "0 24px" }}><div style={{ marginBottom: 30 }}>{settings.eyebrowVisible && <div style={{ color: "#7d6cf0", letterSpacing: 2, fontSize: 12 }}>{settings.eyebrow}</div>}{settings.heroTitleVisible && <h1 style={{ fontSize: 42, margin: "12px 0" }}>{settings.heroTitle}</h1>}{settings.heroDescriptionVisible && <p style={{ color: "#778197" }}>{settings.heroDescription}</p>}</div>{selected ? <div style={{ display: "grid", gridTemplateColumns: "1.4fr 1fr", gap: 24 }}><article style={{ background: "white", borderRadius: 22, overflow: "hidden", boxShadow: "0 12px 40px #1720330d" }}>{selected.coverImage && <img src={selected.coverImage} alt="" style={{ width: "100%", height: 280, objectFit: "cover" }} />}<div style={{ padding: 28 }}><span style={{ color: "#7d6cf0", fontSize: 13 }}>{selected.tag} · {selected.source}</span><h2 style={{ fontSize: 30, lineHeight: 1.3 }}>{selected.title}</h2><p style={{ whiteSpace: "pre-wrap", lineHeight: 1.9, color: "#4d5870" }}>{selected.rewrittenContent || selected.excerpt}</p></div></article><aside><h3>最新发布</h3>{items.map(item => <button key={item.id} onClick={() => setSelected(item)} style={{ display: "block", width: "100%", textAlign: "left", border: 0, background: item.id === selected.id ? "#eeeaff" : "white", borderRadius: 14, padding: 16, marginBottom: 10, cursor: "pointer" }}><b>{item.title}</b><small style={{ display: "block", color: "#8790a4", marginTop: 8 }}>{item.tag} · {item.time}</small></button>)}</aside></div> : <div style={{ padding: 60, background: "white", borderRadius: 20, color: "#8790a4" }}>暂无已发布内容，后台审核发布后会显示在这里。</div>}</section></main>;
}
